services:
  mediaflick:
    build:
      context: ..
      dockerfile: Dockerfile
    init: true
    ports:
      - "3867:3867"
    environment:
      FRONTEND_PORT: "3867"
      BACKEND_PORT: "5000"
      TZ: UTC
    volumes:
      - /opt/mediaflick/config:/app/backend-bun/config
      - /opt/mediaflick/logs:/app/backend-bun/logs
      - /mnt/zurg:/mnt/zurg:rshared
      - /mnt/organized:/mnt/organized
      - /mnt/organized2:/mnt/organized2
    restart: unless-stopped
